---
- name: pull docker image from registry
  remote_user: '{{ user_host }}'
  sudo: yes
  hosts: '{{ target }}'
  tasks:
    - name: login to docker registry
      docker_login:
        registry: '{{ registry_url }}'
        username: '{{ docker_user }}'
        password: '{{ docker_pass }}'
        reauthorize: yes

    - name: pull from registry
      docker_image:
        name: "{{ registry_url }}"/"{{ docker_image }}"
