---
- name: pull docker image from registry
  remote_user: '{{ user_host }}'
  sudo: yes
  hosts: '{{ target }}'
  tasks:
    - name: login to docker registry
      command: docker login {{ registry_url }} -u="{{ docker_user }}" -p="{{ docker_pass }}"
