---
- name: run docker image
  remote_user: '{{ user_host }}'
  sudo: yes
  hosts: '{{ target }}'
  tasks:      
    - name: pull image on slave
      command: docker run -d -p 80:8080 {{ registry_url }}/{{ docker_image }}
